
//we may make a function to change the theme of our game

	//Game BASIC
enum UI_WIDGET_TAG
{
	MENU_AUDIOS,
	EXIT_GAME_BUTTON,
	AUDIO_BG_BUTTON,
	AUDIO_EFFECT_BUTTON,
	AUDIO_TITLE_LABEL,
	AUDIO_TOUCH_START,
	WELCOME_LABEL,
	WELCOME_MENU,
	GAME_MENU,
	GAME_SCENE_START,
	GAME_SCENE_PAUSE,
	GAME_SCENE_RESUME,
	GAME_SCENE_RESET,
	GAME_SCENE_GO_BACK
};